#!/usr/bin/env bash
L_USER="$(cat /tmp/archroot_localuser 2> /dev/null)"

err() { echo -e "\e[1;31m==> Error:\e[0m $@" && exit 1; }
msg() { echo -e "\e[1;32m==> $@ \e[0m"; }

msg "Initializing pacman keyrings..."
pacman-key --init
pacman-key --populate archlinux
msg "Installing essential packages..."
pacman -Syyu base base-devel xorg pulseaudio nano git --noconfirm
msg "Installing servicectl..."
mkdir -p /usr/local/share/servicectl/enabled
curl -L "https://raw.githubusercontent.com/lemniskett/servicectl/master/servicectl" > /usr/local/share/servicectl/servicectl 2> /dev/null
curl -L "https://raw.githubusercontent.com/lemniskett/servicectl/master/serviced" > /usr/local/share/servicectl/serviced 2> /dev/null
chmod +x /usr/local/share/servicectl/service{d,ctl}
ln -s /usr/local/share/servicectl/servicectl /usr/local/bin/servicectl
ln -s /usr/local/share/servicectl/serviced /usr/local/bin/serviced
msg "Setting up locale..."
sed -i 's\#en_US.UTF-8 UTF-8.*\en_US.UTF-8 UTF-8\' /etc/locale.gen
locale-gen
echo "LANG=en_US.UTF-8" > /etc/locale.conf
msg "Setting up timezone..."
echo "Enter your timezone, for example: \"Asia/Jakarta\": " 
while true; do
	read TIMEZONE && \
    [[ -f /usr/share/zoneinfo/$TIMEZONE ]] && \
    ln -s /etc/localtime && \
    ln -s /usr/share/zoneinfo/$TIMEZONE /etc/localtime && \
    break || err "Timezone not found"
done
msg "Creating user account..."
useradd -M $L_USER
gpasswd -a $L_USER wheel
echo "Enter new password for root"
while true; do
	passwd && break
done
echo "Enter new password for $L_USER"
while true; do
	passwd $L_USER && break
done

sed -i 's_# %wheel ALL=(ALL) NOPASSWD: ALL_%wheel ALL=(ALL) NOPASSWD: ALL_' /etc/sudoers
touch /etc/archroot

# Bash Archroot Prompt
[[ -f /home/$L_USER/.bashrc ]] && echo "

# Archroot Prompt
[[ -f /etc/archroot ]] && export PS1=\"(Archroot) \$PS1\"
[[ -f /etc/archroot ]] && cd ~
" >> /home/$L_USER/.bashrc

# ZSH Archroot Prompt
[[ -f /home/$L_USER/.zshrc ]] && echo "

# Archroot Prompt
[[ -f /etc/archroot ]] && export PS1=\"(Archroot) \$PS1\"
[[ -f /etc/archroot ]] && cd ~
" >> /home/$L_USER/.zshrc && \
if cat /home/$L_USER/.zshrc | grep "oh-my-zsh.sh" &> /dev/null; then
    OMZ_CHK="$(grep "oh-my-zsh.sh" /home/$L_USER/.zshrc)"
    [[ $OMZ_CHK = *"oh-my-zsh.sh"* ]] && \
    sed -i '/.*oh-my-zsh.sh/i [[ -f /etc/archroot ]] && ZSH_COMPDUMP="$HOME/.zcompdump-archroot"' /home/$L_USER/.zshrc
fi
